version: '3.8'

services:
  video-caption-generator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./videos:/app/videos  # Mount your video directory here
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-production-secret-key
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
